apiVersion: v1
kind: Service
metadata:
  name: freelancex-apigateway-service
spec:
  selector:
    app: apigateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
