apiVersion: v1
kind: Service
metadata:
  name: freelancex-apigateway-service
spec:
  type: LoadBalancer  
  selector:
    app: apigateway-service
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8080 
