name: CD - Deploy API Gateway to GKE

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: freelancex-cluster
          location: asia-south1-a
          project_id: freelancex-463106

      - name: Create/Update K8s Secret for API Gateway
        run: |
          kubectl create secret generic apigateway-secret \
            --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            --from-literal=PORT="${{ secrets.PORT }}" \
            --from-literal=REDIS_ADDR="${{ secrets.REDIS_ADDR }}" \
            --from-literal=USER_SERVICE_GRPC_ADDR="${{ secrets.USER_SERVICE_GRPC_ADDR }}" \
            --from-literal=PROPOSAL_SERVICE_GRPC_ADDR="${{ secrets.PROPOSAL_SERVICE_GRPC_ADDR }}" \
            --from-literal=CRM_SERVICE_GRPC_ADDR="${{ secrets.CRM_SERVICE_GRPC_ADDR }}" \
            --from-literal=TIMELOG_SERVICE_GRPC_ADDR="${{ secrets.TIMELOG_SERVICE_GRPC_ADDR }}" \
            --from-literal=MESSAGE_SERVICE_GRPC_ADDR="${{ secrets.MESSAGE_SERVICE_GRPC_ADDR }}" \
            --from-literal=INVOICE_SERVICE_GRPC_ADDR="${{ secrets.INVOICE_SERVICE_GRPC_ADDR }}" \
            --from-literal=GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
            --from-literal=GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
            --from-literal=GOOGLE_REDIRECT_URL="${{ secrets.GOOGLE_REDIRECT_URL }}" \
            --from-literal=RAZORPAY_KEY_ID="${{ secrets.RAZORPAY_KEY_ID }}" \
            --from-literal=RAZORPAY_KEY_SECRET="${{ secrets.RAZORPAY_KEY_SECRET }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Kubernetes resources
        run: |
          kubectl apply -f k8s/apigateway-service/deployment.yaml
          kubectl apply -f k8s/apigateway-service/service.yaml
