name: CI - Build & Push API Gateway Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env file
        run: |
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "REDIS_ADDR=${{ secrets.REDIS_ADDR }}" >> .env
          echo "USER_SERVICE_GRPC_ADDR=${{ secrets.USER_SERVICE_GRPC_ADDR }}" >> .env
          echo "PROPOSAL_SERVICE_GRPC_ADDR=${{ secrets.PROPOSAL_SERVICE_GRPC_ADDR }}" >> .env
          echo "CRM_SERVICE_GRPC_ADDR=${{ secrets.CRM_SERVICE_GRPC_ADDR }}" >> .env
          echo "TIMELOG_SERVICE_GRPC_ADDR=${{ secrets.TIMELOG_SERVICE_GRPC_ADDR }}" >> .env
          echo "MESSAGE_SERVICE_GRPC_ADDR=${{ secrets.MESSAGE_SERVICE_GRPC_ADDR }}" >> .env
          echo "INVOICE_SERVICE_GRPC_ADDR=${{ secrets.INVOICE_SERVICE_GRPC_ADDR }}" >> .env
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "GOOGLE_REDIRECT_URL=${{ secrets.GOOGLE_REDIRECT_URL }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> .env

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: aswinputhukaatil/freelancex_apigateway_service:latest
